apiVersion: v1
kind: Pod
metadata: 
  name: nginx4
  labels: 
    name: nginx4
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: new-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: new-volume
      hostPath:
        path: /usr/share/nginx/html
