apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
    - name: nginx
      image: adisharma96/nginx:v1
      ports:
        - containerPort: 80
      volumeMounts:
        - name: testing-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: testing-volume
      persistentVolumeClaim:
        claimName: my-pvc-claim
