apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-claim
spec:
  selector:
    matchLabels:
      storage: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
