apiVersion: v1
kind: ReplicationController
metadata: 
  name: nginx-rc
spec:
  replicas: 3
  selector:
    name: nginx-app
  template:
    metadata:
      name: nginx-app
      labels:
        name: nginx-app
    spec:
     containers:
       - name: nginx
         image: nginx:latest
         ports:
           - containerPort: 80
