apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    name: nginx2
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts: 
        - name: nginx-volume3
          mountPath: /usr/share/nginx/html
    - name: tomcat
      image: tomcat:latest
      volumeMounts:
        - name: nginx-volume3
          mountPath: /etc
  volumes:
    - name: nginx-volume3
      emptyDir: {}

