- 
  name: testing service modules
  hosts: servers
  tasks:
    - name: service module
      service:
        name: nginx
        state: started
    - name: start vsftpd service
      service:
        name: vsftpd
        state: started
    - name: edit /etc/hosts file
      lineinfile:
        destfile: /etc/hosts
        line: '127.0.0.1 {{ item }}'
      with_items:
        - web
        - abc
        - bca  
